version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - mynetwork

  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH:neo4j/12345678
    networks:
      - mynetwork

  python-scripts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_scripts
  
    depends_on:
      - mongo
      - cassandra
      - neo4j
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
      
    

